			<div class="col-lg-8 col-lg-offset-2 text-left">
			<img src="img/profile2.jpg" class="img-circle" align="left" width="150" height="150" style="margin: 10px">
			<P/>
			Hi, I am Ying Liu, I started programming when I was in middle school as a science class assignment to create a webpage. Back then Pokemon was the hottest cartoon in town, so off course I created a web 1.0 website on angelfire.com's free hosting about the little pocket monsters. What started as a science class assignment, grew to a three year project where at its peak was receiving approximately one million pageviews per month. Through that experience I learned how to use ws_ftp, adobe photoshop 5.0, html 2.0, plain old javascript, and a little bit of perl scripting. However, my "relationship" with programming took a detour because of parents influence and I went on to study accounting. 
			<P/>
			I graduated from University of Florida with a Bachelors in Accounting and went on to work as a Financial Statements Auditor for almost two years before heading back to University of Florida to get my Masters in Information Systems and Operations Management. During graduate school, I interned at JP Morgan Chase & Co's (JPMC) technology department and it reignited my love for building things. I went on to work part-time while I continued graduate school and then joined JPMC full-time.. 
			<P/>
			Around two years later, a senior trader at First New York reached out with an opportunity to join an algorithmic trading desk and build your own trading business. I took the leap because well, who havent dreamt of working for wallstreet and cruising in mega yachts right? ;) At this point I have built a consistently profitable set of algorithmic trading strategies. It wasn't easy and still isn't easy. It is a great learning experience and with a dataset as large as the 8000+ stocks' tick data, it has proven Murphy's law many times. However, at this point I really want to continue my childhood project of building web applications.
			<P/>
			I am a passionate and hard working self-starter that's looking for an opportunity to continue to learn and build something great! 
			</div>